name: CI and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    name: Execute Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install
      - run: npm run test

  e2e-tests:
    name: Execute End-to-End Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install
      - run: npx playwright install --with-deps
      - run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          cat .env
          export $(cat .env | xargs)
          npx prisma migrate deploy
      - run: |
          echo "Resetting Database..."
          npx prisma migrate reset --force
      - run: npm run build
      - run: |
          nohup npm run start -- -p 3000 > nextjs.log 2>&1 &
          sleep 5
        env:
          NODE_ENV: production
          PORT: 3000
      - if: failure()
        run: cat nextjs.log
      - run: |
          echo "Waiting for Next.js to start..."
          for i in {1..60}; do
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000 || echo "000")
            if [[ "$STATUS_CODE" == "200" ]]; then
              echo "Next.js is up!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 2
          done
        timeout-minutes: 3
      - run: E2E_TEST=true npm run test:e2e
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/

  preview-deploy:
    name: Deploy Preview to Vercel
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install
      - run: npm run build
      - run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm --scope ${{ secrets.VERCEL_ORG_ID }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  production-deploy:
    name: Deploy Production to Vercel
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install
      - run: npm run build
      - run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
